---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Tests and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Lint
        run: docker compose run --rm app sh -c "flake8"

      # - name: Check EC2 Status
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
